// ElectionStatistics.WebSite/ClientApp/components/NavMenu.tsx
import * as React from 'react';
import { NavLink, Link } from 'react-router-dom';

export class NavMenu extends React.Component<{}, {}> {
    public render() {
        return <div className='main-nav'>
                <div className='navbar navbar-inverse'>
                <div className='navbar-header'>
                    <button type='button' className='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
                        <span className='sr-only'>Toggle navigation</span>
                        <span className='icon-bar'></span>
                        <span className='icon-bar'></span>
                        <span className='icon-bar'></span>
                    </button>
                    <Link className='navbar-brand' to={ '/' }>ElectionStatistics.WebSite</Link>
                </div>
                <div className='clearfix'></div>
                <div className='navbar-collapse collapse'>
                    <ul className='nav navbar-nav'>
                        <li>
                            <NavLink exact to={ '/' } activeClassName='active'>
                                <span className='glyphicon glyphicon-home'></span> Home
                            </NavLink>
                        </li>
                        <li>
                            <NavLink to={ '/counter' } activeClassName='active'>
                                <span className='glyphicon glyphicon-education'></span> Counter
                            </NavLink>
                        </li>
                        <li>
                            <NavLink to={ '/fetchdata' } activeClassName='active'>
                                <span className='glyphicon glyphicon-th-list'></span> Fetch data
                            </NavLink>
                        </li>
                    </ul>
                </div>
            </div>
        </div>;
    }
}

// ElectionStatistics.WebSite/ClientApp/app/components/navmenu/navmenu.component.ts
﻿import { Component } from '@angular/core';

@Component({
	 selector: 'nav-menu',
	 templateUrl: './navmenu.component.html',
	 styleUrls: ['./navmenu.component.css']
})
export class NavMenuComponent {
}

﻿<div class='main-nav'>
	 <div class='navbar navbar-inverse'>
		 <div class='navbar-header'>
			 <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
				 <span class='sr-only'>Toggle navigation</span>
				 <span class='icon-bar'></span>
				 <span class='icon-bar'></span>
				 <span class='icon-bar'></span>
			 </button>
			 <a class='navbar-brand' [routerLink]="['/home']">Election Statistics</a>
		 </div>
		  <div class='clearfix'></div>
		  <div class='navbar-collapse collapse'>
				<ul class='nav navbar-nav'>
					 <li [routerLinkActive]="['link-active']">
						  <a [routerLink]="['/about']">
								<span class='glyphicon glyphicon-home'></span> О сайте
						  </a>
					 </li>
					 <li [routerLinkActive]="['link-active']">
						  <a [routerLink]="['/fetch-data']">
								<span class='glyphicon glyphicon-th-list'></span> Fetch data
						  </a>
					 </li>
				</ul>
		  </div>
	 </div>
</div>
